Homepage content
Journey-bites/journey-bites-website pull request #12
Opened 2024-05-26 09:04 UTC by jweeei

- 增加創作者列表、熱門景點
- 調整 Email 註冊頁標題跑版

首頁內容初版完成，結構未來會在調整

2024-05-26 10:34 UTC, ba1679 requested changes

2024-05-26 10:34 UTC, ba1679 commented on src/app/(global)/layout.tsx
>      </>
`Content` 整個要放在 page.tsx，不然在首頁底下的頁面都會吃到這個樣式，ex: /search 頁面，這個 content 應該只會出現在首頁，所以放在自己的頁面才適當

2024-05-26 10:34 UTC, ba1679 commented on src/app/(global)/loadding.tsx
loadding -> loading

2024-05-26 10:34 UTC, ba1679 commented on src/components/articleCardTemplate.tsx
component 的檔名首字應該要大寫比較好

2024-05-26 15:46 UTC, LTK228 approved these changes

2024-05-27 07:41 UTC, CoolizzLuo reviewed
Needs Work

2024-05-27 07:41 UTC, CoolizzLuo commented on src/app/(global)/loadding.tsx
> +                    <Skeleton className='w-full h-[20px] mb-2' />
`h-[20px]` 改用 `h-5`

2024-05-27 07:41 UTC, CoolizzLuo commented on src/app/(global)/loadding.tsx
> +                <Skeleton className='w-[40px] h-[40px] rounded-full' />
`w-[40px] h-[40px]` 改用 `w-10 h-10`

2024-05-27 07:41 UTC, CoolizzLuo commented on src/app/(global)/loadding.tsx
> +                <Skeleton className='w-[100px] h-[20px] ml-2' />
`h-[20px]` 改用 `h-5`

2024-05-27 07:41 UTC, CoolizzLuo commented on src/components/popularAttractions.tsx
`attractionClass ` 看起來不需要拆出來

2024-05-27 07:41 UTC, CoolizzLuo commented on src/components/popularAttractions.tsx
> +        <div  key={item} className='mr-3 mb-4'>
div 這有多一個空格

2024-05-27 07:41 UTC, CoolizzLuo commented on src/components/popularAttractions.tsx
> +          <a href='' className={attractionClass}>{item}</a>
使用 next 原生地 link 取代 a tag

2024-05-27 17:17 UTC, ayugioh2003 commented on src/components/popularAttractions.tsx
> +        <div  key={item} className='mr-3 mb-4'>
印象你們好像有裝 eslint 跟 prettier？
用 VSCode 的 formatter 應該可以自動修復這個問題

(小麥)

2024-05-28 01:09 UTC, ba1679 commented on src/components/popularAttractions.tsx
> +        <div  key={item} className='mr-3 mb-4'>
rules 可能要再設定完整一點，我再另外開 branch 處理

2024-05-28 10:01 UTC, ba1679 approved these changes
LGTM

2024-05-28 10:03 UTC, merged