Feat/footer
Journey-bites/journey-bites-website pull request #17
Opened 2024-05-31 21:49 UTC by pavlo1031

2024-06-01 08:07 UTC, pavlo1031 commented
there's still some issues to fix

2024-06-01 09:10 UTC, pavlo1031 commented
- reopen the pull request after fixing a "build failure" issue
  (add explicit type on variable name)

2024-06-01 10:10 UTC, ba1679 requested changes

2024-06-01 10:10 UTC, ba1679 commented on src/components/Footer.tsx
> +'use client';
[Suggested] 'use client' 目前專案中都有空一行
```suggestion
'use client';

```

2024-06-01 10:10 UTC, ba1679 commented on src/components/Footer.tsx
> +import MouseEvent from 'react';
[Required] MouseEvent 是從 'react' 解構出來的
```suggestion
import { MouseEvent } from 'react';
```

2024-06-01 10:10 UTC, ba1679 commented on src/components/Footer.tsx
> +    return false;
[Suggested] 有了 TypeScript 這邊的檢查就不需要了，然後感覺只需要 e.preventDefault() ?
```suggestion
      e.preventDefault();
```

2024-06-01 10:10 UTC, ba1679 commented on src/components/Footer.tsx
> +      </div>
[Required]  
1. 沒用到的 className 要移除
2. 直接用 Image 就好，外面不用再多一層 div (改了之後上面 onContextMenuHandler 要改成 HTMLImageElement)
```suggestion
       <Image src={Logo} className='object-cover object-center w-[200px] sm:w-[240px] md:w-[240px] lg:w-[245px] xl:w-[250px]' onContextMenu={onContextMenuHandler} alt='Journey Bites' priority />
        <Image src={CurveLine} className='mt-[-6px] mb-3 lg:mb-3.5' onContextMenu={onContextMenuHandler} alt='' />
```

2024-06-01 10:10 UTC, ba1679 commented on src/components/Footer.tsx
> +      <div className='footer-curve-line mt-[-6px] mb-3 lg:mb-3.5' onContextMenu={onContextMenuHandler}>
為什麼要 mt 負數 mb 又正數？

2024-06-01 10:10 UTC, ba1679 commented on tailwind.config.ts
> +      21: '96px'
[Suggested] 看起來目前只有用到 13, 14，後面可以先不用加

2024-06-01 11:44 UTC, pavlo1031 commented
there's still other something to fix.

2024-06-01 12:01 UTC, pavlo1031 commented
- fix issues (mostly eslint issues)
- apply coding suggestions from Render Lai.

2024-06-01 13:20 UTC, ba1679 commented on tailwind.config.ts
> +      21: '96px'
[Required] 1 個單位是 4px，13 的話會是 13 * 4

2024-06-01 20:12 UTC, pavlo1031 commented on src/components/Footer.tsx
> +    return false;
> "這邊的檢查就不需要了"

妳指的是 對於 **e.preventDefault != undefined** 和 **e.stopPropagation != undefined**
這樣的檢查嗎？

2024-06-01 20:15 UTC, pavlo1031 commented on src/components/Footer.tsx
> +      <div className='footer-curve-line mt-[-6px] mb-3 lg:mb-3.5' onContextMenu={onContextMenuHandler}>
用了不太正統的方式微調
待重新調整，一處一處的和Figma校對

2024-06-01 20:16 UTC, pavlo1031 commented on src/components/Footer.tsx
> +      </div>
已排入我的待修改清單 👌
（但是是在「Figma校對設計稿」之後）

2024-06-01 20:24 UTC, pavlo1031 commented on src/components/Footer.tsx
> +import MouseEvent from 'react';
✅ 已在 2024/6/01 19:38 的 commit : 5880082  修改完畢
      （引入 MouseEventHandler時，一併和 MouseEvent 以此種 import方式）

2024-06-01 20:27 UTC, pavlo1031 commented on src/components/Footer.tsx
> +'use client';
✅ 已在 2024/6/01 19:43 的 commit : a963717 修改完畢

2024-06-01 20:31 UTC, pavlo1031 commented on tailwind.config.ts
> +      21: '96px'
- 👌 已排入我的待修改清單
（但是是在「Figma校對設計稿」之後）
- 修正space level數值時，以及拿掉沒用到的spacing level，只留下需要的時
會注意它們的級距 要保持在4px

2024-06-02 00:52 UTC, CoolizzLuo commented on src/components/Footer.tsx
> +    return false;
不用判斷是不是 undefined，因為已經加上 type

2024-06-02 00:52 UTC, CoolizzLuo commented on src/components/Footer.tsx
> +      </div>
alt 都要寫不要留空字串

2024-06-02 01:06 UTC, pavlo1031 commented on src/components/Footer.tsx
> +      </div>
@CoolizzLuo 所以 footer curve line 它的<Image> 的 alt 也要寫 'Jouney Bites' ？

2024-06-02 01:14 UTC, pavlo1031 commented on src/components/Footer.tsx
> +    return false;
@CoolizzLuo, @ba1679 
➜ 已在 2024/6/02 08:58 的 commit : 56da986 移除此判斷 : "**undefined check**"

2024-06-02 01:21 UTC, pavlo1031 commented on src/components/Footer.tsx
> +      </div>
「為 <Image> 的 alt屬性都加上值」這個程式碼改動
 commit message **prefix** 要寫什麼啊？

2024-06-02 01:34 UTC, CoolizzLuo commented on src/components/Footer.tsx
> +      </div>
要寫出這個圖片是幹嘛，像是 logo 就寫 logo 方便 SEO 閱讀，也方便在圖片沒有顯示的時候有文字知道這是做什麼
改動的話寫 `fix` 就好了

2024-06-02 01:36 UTC, pavlo1031 commented on src/components/Footer.tsx
> +      </div>
那 footer curve line 的 alt 該寫什麼呢？
那個純粹是裝飾啊

2024-06-02 01:38 UTC, CoolizzLuo commented on src/components/Footer.tsx
> +      </div>
就寫個  wave 或 curve 之類都可以

2024-06-02 01:46 UTC, pavlo1031 commented on src/components/Footer.tsx
> +      </div>
> https://github.com/Journey-bites/journey-bites-website/pull/17#discussion_r1623304628
> "alt 都要寫不要留空字串"

➜ 已在 2024/6/02 09:42 的 commit : c205505  修改完畢

2024-06-02 02:02 UTC, pavlo1031 commented on src/components/Footer.tsx
> +      </div>
> "alt 都要寫不要留空字串"

➜ 已在 2024/6/02 09:42 的 commit : c205505  修改完畢

2024-06-02 13:02 UTC, ba1679 commented
Due to a reallocation of tasks, I will be taking over the implementation of the footer UI in another PR.

2024-06-02 13:02 UTC, closed without merging