add text editor v1
Journey-bites/journey-bites-website pull request #24
Opened 2024-06-10 20:01 UTC by jweeei

新增編輯器功能

-  上傳圖片(網址連結)
-  Link (預設在編輯器阻擋外連)
-  文本對齊

預計新增功能

-  Numbered list
-  Unordered list

2024-06-11 10:52 UTC, ba1679 commented
有衝突

2024-06-14 08:37 UTC, ba1679 requested changes
衝突再解一下

2024-06-14 08:37 UTC, ba1679 commented on .gitignore
> +.env
其實把 local 的環境變數放在 `.env.local` 檔裡即可
https://nextjs.org/docs/pages/building-your-application/configuring/environment-variables#loading-environment-variables

2024-06-14 08:37 UTC, ba1679 commented on src/components/editor/EditorDialog.tsx
> +const schema = z.string().refine(val => val.startsWith('https://'), { message: 'URL must start with https' });
```suggestion
const schema = z.string().url({ message: '請填入正確的網址格式, ex: https://www.journeybites.com' })).or(z.literal(''))
```
zod 有提供 url 驗證，加 `.or(z.literal(""))` 表示 optional，算是 zod 小問題，message 建議用中文(可自訂)保持跟目前風格一致

2024-06-14 08:37 UTC, ba1679 commented on src/lib/useDialog.ts
zustand store 應該放在 stores folder 底下，命名建議用 `dialogStore`，用 `useDialog` 會誤以為是 custom hook

2024-06-14 08:37 UTC, ba1679 commented on src/components/editor/settings.ts
常數可以放在 constants folder 底下，命名改為 `editorSettings` 之類的，常數的命名目前專案都用 Upper Snake Case，建議改成一樣保持一致性 ex: `COMMON_CLASS_NAME`

2024-06-14 08:37 UTC, ba1679 commented on src/components/editor/Tiptap.tsx
> +import Link from '@tiptap/extension-link';
Image & Link 建議重新命名一下，避免跟 Next 提供的搞混

2024-06-14 08:37 UTC, ba1679 commented on src/app/(global)/article/create/page.tsx
這頁應該要放到 `(dashboard)` 底下，才會檢查是否有登入，沒登入不能進入

2024-06-14 08:37 UTC, ba1679 commented on src/components/editor/Toolbar.tsx
> +  Image as Img,
lucide-react 有提供 `ImageIcon` 這個命名可以使用，就不用另外 as

2024-06-14 08:37 UTC, ba1679 commented on src/components/editor/EditorDialog.tsx
Component 命名跟檔名建議一致，看起來只針對圖片上傳才會用到，是否先改成 ImageUploadDialog 就好？

2024-06-14 08:37 UTC, ba1679 commented on src/components/editor/EditorDialog.tsx
> +  dialog: (url: string) => void;
```suggestion
  handleDialog: (url: string) => void;

```

2024-06-14 08:37 UTC, ba1679 commented on src/components/editor/EditorDialog.tsx
> +  };
目前專案是用 React hook form 處理表單，有興趣的話可以改一下

2024-06-14 08:37 UTC, ba1679 commented on src/components/editor/EditorDialog.tsx
> +  };
如果維持原寫法的話，finally 那段我有點疑惑，可能需要講解一下，另外有 errors 的話建議也要處理對應 UI (button disabled, error message...)
33 & 45 行都有 setData 這邊要改一下

(總而言之改 react hook form 比較輕鬆)

2024-06-14 08:37 UTC, ba1679 commented on src/components/editor/EditorDialog.tsx
> +              className='col-span-3'
Input 應該可以讓他滿寬，三欄太短了有點奇怪

2024-06-14 08:37 UTC, ba1679 commented on src/components/editor/EditorWrapper.tsx
> +      <div className='mb-10 text-center text-3xl text-primary-300'>
form 如果直接在 `Tiptap.tsx `裡面，“新增文章” 標題部分直接寫在 `page.tsx` 內如何？

2024-06-14 14:42 UTC, jweeei commented on src/components/editor/EditorDialog.tsx
> +const schema = z.string().refine(val => val.startsWith('https://'), { message: 'URL must start with https' });
雖然是驗心酸的，還是限制一下使用 https

2024-06-14 14:46 UTC, jweeei commented on src/components/editor/settings.ts
在 tiptop 的 extensions 這邊還是別名使用小寫

2024-06-14 14:47 UTC, jweeei commented on src/components/editor/EditorDialog.tsx
插入連結會使用到

2024-06-14 14:50 UTC, jweeei commented on src/components/editor/EditorDialog.tsx
> +  };
因為使用 onInput 事件，當欄位的值變動就會儲存到 store，finally 只是將上次暫存的值清掉，寫這邊的時候很趕，hook form 有考慮但沒時間看，有時間再改寫

2024-06-15 01:34 UTC, ba1679 approved these changes
時程關係，剩餘優化修改之後再處理

2024-06-15 09:54 UTC, jweeei commented
先進行合併，後續再優化

2024-06-15 10:01 UTC, merged