Feat/edit article permission
Journey-bites/journey-bites-website pull request #42
Opened 2024-06-26 17:51 UTC by jweeei

- 增加編輯文章權限，現在無法進入別人的編輯區
- 編輯器圖片及發佈設定縮圖加上驗證規則(允許 imgur  unsplash)

2024-06-27 00:13 UTC, ba1679 commented
開 PR 前需注意一下最新的 main，有衝突～

2024-06-28 06:56 UTC, ba1679 requested changes
有滿多不需要的註解，建議拿掉～

2024-06-28 06:56 UTC, ba1679 commented on src/app/(global)/(dashboard)/article/edit/[id]/page.tsx
> +    mutationFn: getArticleById,
fetch data 應該用 useQuery

2024-06-28 06:56 UTC, ba1679 commented on src/lib/utils.ts
> +};
這邊做的事情很單純，只需要比對 ID，應該可以直接寫在用到的地方就好

2024-06-28 06:56 UTC, ba1679 commented on src/app/(global)/(dashboard)/article/publish/[id]/page.tsx
> +    // thumbnailUrl: z.string().optional().refine(val => !val || urlRegex.test(val), { message: '請至 imgur 或 unsplash 上傳圖片，造成不便敬請見諒' }),
沒用到的應該可以直接刪掉了，之後要優化應該也不會用這種方式

2024-06-28 06:56 UTC, ba1679 commented on src/app/(global)/(dashboard)/article/publish/[id]/page.tsx
> +    // editArticleMutate(editArticleRequest);
這邊應該不用了？

2024-06-28 06:56 UTC, ba1679 commented on src/app/(global)/(dashboard)/article/publish/page.tsx
不必要的註解建議都拿掉

2024-06-28 06:56 UTC, ba1679 commented on src/constants/imgUrlValidate.ts
> +  });
```suggestion
  const schema = z.string().url({ message: '請填入正確的網址格式, ex: https://www.journeybites.com' }).or(z.literal(''));

```
zod url 就會檢查 https 了

2024-06-28 06:56 UTC, ba1679 commented on src/app/(global)/(dashboard)/article/edit/[id]/page.tsx
> +        router.replace('/login');
這個在外層 layout 就有做了

2024-06-28 06:56 UTC, ba1679 commented on src/app/(global)/(dashboard)/article/edit/[id]/page.tsx
> +        return;
沒有 id 就不會進來這頁，這個應該永遠不會跑到

2024-06-28 06:56 UTC, ba1679 commented on src/app/(global)/(dashboard)/article/edit/[id]/page.tsx
> +    fetchArticle();
用 useQuery 就不用這個了

2024-06-30 02:14 UTC, ba1679 commented on src/app/(global)/layout.tsx
> +const isCreatePage = pathname === '/article/create';
```suggestion
const articlePathRegex = /^\/article\/(publish(\/[a-f0-9]+)?|create|edit\/[a-f0-9]+)$/;
const shouldHideHeader =  articlePathRegex.test(pathname);
```
https://regex101.com/r/QbxKxV/1

2024-06-30 13:47 UTC, ba1679 commented on src/app/(global)/layout.tsx
> +  const isEditPage = pathname.startsWith('/article/edit/') && pathname.split('/').length === 4;
`pathname.split('/').length === 4` 實在是不易讀
另外要取得 id 可以用 Next.js 提供的 [useParams](https://nextjs.org/docs/app/api-reference/functions/use-params) API

2024-07-04 19:29 UTC, jweeei commented
- 建立、編輯、文章發布區顯示頭部

![螢幕擷取畫面 2024-07-05 032040](https://github.com/Journey-bites/journey-bites-website/assets/136718584/7ab57406-8ea4-4ab6-9af8-1169a5728594)

2024-07-05 00:54 UTC, ba1679 approved these changes
一些小建議～其他 LGTM

2024-07-05 00:54 UTC, ba1679 commented on src/components/Header/HeaderButtons.tsx
> +                }
應該是整個 Button 都隱藏才比較合理

2024-07-05 00:54 UTC, ba1679 commented on src/app/(global)/(dashboard)/article/create/page.tsx
> +import { PencilLine } from 'lucide-react';
[Suggested] 其實專案內其他地方是習慣把外部的 dependency 都從最上面開使 import 排列

2024-07-05 01:12 UTC, CoolizzLuo reviewed
some suggestions

2024-07-05 01:12 UTC, CoolizzLuo commented on src/app/(global)/(dashboard)/article/edit/[id]/page.tsx
> +  const [editContent, setEditContent] = useState<Article | undefined>(undefined);
這個名字好像不太好？ editingContent 之類會好點

2024-07-05 01:12 UTC, CoolizzLuo commented on src/app/(global)/(dashboard)/article/edit/[id]/page.tsx
> +      setEditContent(data);
這似乎不用拉一個 state 存，沒有其他地方會去用

2024-07-05 01:12 UTC, CoolizzLuo commented on src/app/(global)/(dashboard)/article/edit/[id]/page.tsx
> +        verifyAuthor(creator?.id, auth.id, router, () => setIsAuthor(true));
如果 data 有資料 creator 就會有 id 應該不需要 `?.`

2024-07-05 01:12 UTC, CoolizzLuo commented on src/app/(global)/(dashboard)/article/edit/[id]/page.tsx
> +      }
只有 console.log 好像沒意義

2024-07-05 01:12 UTC, CoolizzLuo commented on src/app/(global)/(dashboard)/article/edit/[id]/page.tsx
> +      )}
兩層三元不建議，可讀性會很差，沒有權限編輯建議另外拉出來 early return

2024-07-05 01:12 UTC, CoolizzLuo commented on src/app/(global)/(dashboard)/article/edit/[id]/page.tsx
>    searchParams: { [key: string]: string | string[] | undefined }
這邊沒用到 searchParams 可以不用寫

2024-07-05 01:12 UTC, CoolizzLuo commented on src/app/(global)/(dashboard)/article/publish/[id]/page.tsx
這個跟 `edit` 那邊重複邏輯好多 不拆個 hook 之類的嗎？ 感覺會很難維護

2024-07-05 19:12 UTC, jweeei commented on src/app/(global)/(dashboard)/article/publish/[id]/page.tsx
命名、邏輯拆分後續 PR 處理

2024-07-05 19:13 UTC, merged