Homepage
Journey-bites/journey-bites-website pull request #9
Opened 2024-05-21 11:53 UTC by jweeei

增加首頁卡片模板(熱門文章、推薦文章)，有時間再重構

2024-05-21 12:38 UTC, ba1679 requested changes
一些建議跟問題，有空再改就好

2024-05-21 12:38 UTC, ba1679 commented on src/components/articleCardTemplate.tsx
> +  Card as Cd,
應該用 Card 就好？

2024-05-21 12:38 UTC, ba1679 commented on src/components/articleCardTemplate.tsx
> +  title: '熱門文章' | '推薦文章';
我的話可能會另外用 type 去控制樣式，type 可以另外用 enum
```suggestion
  title: '熱門文章' | '推薦文章';
  type:  'hot' | 'recommend';

```

2024-05-21 12:38 UTC, ba1679 commented on src/components/articleCardTemplate.tsx
> +            <div className='absolute top-7 right-9 border-2 border-solid border-blue-600'><a href='' className='block px-4 py-3 text-blue-500'>查看更多</a></div>
個人習慣換行XD

```suggestion
            <div className='absolute top-7 right-9 border-2 border-solid border-blue-600'>
              <a href='' className='block px-4 py-3 text-blue-500'>查看更多</a>
             </div>

```

2024-05-21 12:38 UTC, ba1679 commented on src/components/custom/SocialLink.tsx
> +  );
```suggestion
    <div className='flex'>
       <Eye />
       <span>2333</span>
       <Heart />
       <span>2333</span>
       <Bookmark />
     </div>
  );

```

2024-05-21 12:38 UTC, ba1679 commented on tailwind.config.ts
> +        // '2xl': '1400px',
想問這邊的數字定義

2024-05-21 12:38 UTC, ba1679 commented on tailwind.config.ts
> +      },
border 應該可以 className="border-4" 就好

2024-05-21 13:38 UTC, jweeei commented on src/components/articleCardTemplate.tsx
> +  Card as Cd,
這裡會改回 Card，奇怪的是，再 import 的時候 VS code 一直提示衝突，現在本地端是正常的(錯誤訊息忘了紀錄)，不然不會另外改名

2024-05-21 15:22 UTC, jweeei commented on tailwind.config.ts
> +        // '2xl': '1400px',
自定義的 bowser breakpoint，這邊應該要寫在 extend 而不是在 theme 下覆蓋，之後會推一個 commot 更新

2024-05-21 15:28 UTC, jweeei commented on tailwind.config.ts
> +      },
設計稿是 10px，更新在下一個 commit 上

2024-05-22 13:21 UTC, ba1679 commented on src/components/articleCardTemplate.tsx
> +    <>
這邊應該不用包 Fragment

2024-05-23 18:37 UTC, jweeei reviewed
- 因為增加了斷點，有修改到 Header、login、register 頁面
- 要檢查一下 prettier 有沒有正常運作，有些檔案 pull 下來有空格

2024-05-24 11:53 UTC, ba1679 approved these changes
skeleton 好像沒用到，其他 LGTM

2024-05-24 11:53 UTC, ba1679 commented on src/components/ui/skeleton.tsx
這個好像沒用到？

2024-05-24 14:26 UTC, jweeei commented on src/components/ui/skeleton.tsx
開發中

2024-05-24 14:26 UTC, merged